In [152]:
import pandas as pd

In [153]:
employeesDataFrame = pd.read_csv('resources/employees.csv')
employeesDataFrame.head()

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,8/6/1993,12:42 PM,97308,6.945,True,Marketing
1,Thomas,Male,3/31/1996,6:53 AM,61933,4.170,True,NaN
2,Maria,Female,4/23/1993,11:17 AM,130590,11.858,False,Finance
3,Jerry,Male,3/4/2005,1:00 PM,138705,9.340,True,Finance
4,Larry,Male,1/24/1998,4:47 PM,101004,1.389,True,Client Services

In [154]:
# dataframe hakkinda detayli bilgiler verir
# verbose=True detayli bilgiler dondurmesini saglar (varsayilandir), verbose=False daha az detay dondurur
# null_counts parametresi null degerlerin sayisinin dondurulup dondurulmeyecegini belirtir, varsayilan True'dur
employeesDataFrame.info(verbose=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   First Name         933 non-null    object
 1   Gender             855 non-null    object
 2   Start Date         1000 non-null   object
 3   Last Login Time    1000 non-null   object
 4   Salary             1000 non-null   int64
 5   Bonus %            1000 non-null   float64
 6   Senior Management  933 non-null    object
 7   Team               957 non-null    object
dtypes: float64(1), int64(1), object(6)
memory usage: 62.6+ KB

In [155]:
# Start Date column'daki zaman degerlerini pandas sinifindaki datetime nesnelerine donusturur
employeesDataFrame['Start Date'] = pd.to_datetime(employeesDataFrame['Start Date'])
employeesDataFrame['Last Login Time'] = pd.to_datetime(employeesDataFrame['Last Login Time'])

# dataframe'i ice aktarirken date olarak parse edilebilecek alanlari direkt datetime nesnesi olarak ayarlar
employeesDataFrame = pd.read_csv('resources/employees.csv', parse_dates=['Start Date', 'Last Login Time'])

In [156]:
# Senior Managment column'unu boolean degerler olarak tekrardan atar
employeesDataFrame['Senior Management'] = employeesDataFrame['Senior Management'].astype('bool')

In [157]:
# Gender column'unun turunu category olarak ayarlayip tekrardan atar
employeesDataFrame['Gender'] = employeesDataFrame['Gender'].astype('category')

In [158]:
# employeesDataFrame'deki Gender column degeri 'Male' olan alanlar icin True, digerleri icin False olan bir series dondurur
condition = employeesDataFrame['Gender'] == 'Male'

# Team column degeri Finance olan alanlar icin True, digerleri icin False dondurur
condition = emplooyesDataFrame['Team'] == 'Finance'

# Senior Management column'u bool degerler icerir, yani yukarida yaptigimiz sorgulama islemlerinden donen boolean degerler
# iceren series'ler gibi bir series'dir
condition = employeesDataFrame['Senior Management']

# Team column degeri Finance olmayan alanlar icin True, digerleri icin False dondurur
condition = employeesDataFrame['Team'] != 'Finance'

# Salary column degeri 100000'den buyuk olan satirlar icin True, digerleri icin False denk gelecek bir series dondurur
condition = employeesDataFrame['Salary'] >= 100000

# Start Date column degeri belirtilen tarihten yeni olan tarihlerin bulundugu alanlar icin True
# digerleri icin False deger iceren bir series dondurur
condition = employeesDataFrame['Start Date'] > '1990-01-01'

# Gender column degeri 'Male' ve Team column degeri 'Finance' olan alanlar icin True
# digerleri icin False degerler iceren bir series dondurur
# ampersent yerine python'un 've' mantiksal operatoru olan 'and' kullanirsak hata aliriz 
condition = (employeesDataFrame['Gender'] == 'Male') & (employeesDataFrame['Team'] == 'Finance')

# Team column degeri 'Marketing' veya Start Date column degeri '1985-01-01' olan alanlar icin True
# digerleri icin False degerler iceren bir series dondurur
# dikey cizgi yerine python'un 'veya' mantiksal operatoru olan 'or' kullanirsak hata aliriz 
condition = (employeesDataFrame['Team'] == 'Marketing') | (employeesDataFrame['Start Date'] == '1985-01-01')

# Team column degeri 'Marketing' veya Start Date column degeri '1985-01-01' olan ve 
# First Name column degeri 'Robert' alanlar icin True digerleri icin False degerler iceren bir series dondurur
condition = ((employeesDataFrame['Team'] == 'Marketing') | (employeesDataFrame['Start Date'] == '1985-01-01')) & (employeesDataFrame['First Name'] == 'Robert')

# condition'daki True olan alanlarla eslesen satirlari getirir
employeesDataFrame[condition].head()

Empty DataFrame
Columns: [First Name, Gender, Start Date, Last Login Time, Salary, Bonus %, Senior Management, Team]
Index: []

In [159]:
# bu condition ile altindaki condition ayni sonucu uretir
condition = (employeesDataFrame['Team'] == 'Marketing') | (employeesDataFrame['Team'] == 'Product') | (employeesDataFrame['Team'] == 'Finance')

# isin metodu, kendisine verilen kume icindeki degerlerin oldugu satirlar icin True digerleri icin False degerler iceren bir
# series dondurur ve bunu elimizdeki dataframe'i filtrelemek icin kullanabiliriz
condition = employeesDataFrame['Team'].isin({'Marketing', 'Product', 'Finance'})

employeesDataFrame[condition].head()

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,1993-08-06,2023-01-05 12:42:00,97308,6.945,True,Marketing
2,Maria,Female,1993-04-23,2023-01-05 11:17:00,130590,11.858,False,Finance
3,Jerry,Male,2005-03-04,2023-01-05 13:00:00,138705,9.340,True,Finance
6,Ruby,Female,1987-08-17,2023-01-05 16:20:00,65476,10.012,True,Product
7,NaN,Female,2015-07-20,2023-01-05 10:43:00,45906,11.598,True,Finance

In [160]:
# Team column'unda degeri null olan degerler icin True, digerleri icin False degerler iceren bir series dondurur
condition = employeesDataFrame['Team'].isnull()

employeesDataFrame[condition].head()

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
1,Thomas,Male,1996-03-31,2023-01-05 06:53:00,61933,4.170,True,NaN
10,Louise,Female,1980-08-12,2023-01-05 09:01:00,63241,15.132,True,NaN
23,NaN,Male,2012-06-14,2023-01-05 16:19:00,125792,5.042,True,NaN
32,NaN,Male,1998-08-21,2023-01-05 14:27:00,122340,6.417,True,NaN
91,James,NaN,2005-01-26,2023-01-05 23:00:00,128771,8.309,False,NaN

In [161]:
# Team column'unda degeri null olmayan degerler icin True, digerleri icin False degerler iceren bir series dondurur
condition = employeesDataFrame['Team'].notnull()

employeesDataFrame[condition].head()

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,1993-08-06,2023-01-05 12:42:00,97308,6.945,True,Marketing
2,Maria,Female,1993-04-23,2023-01-05 11:17:00,130590,11.858,False,Finance
3,Jerry,Male,2005-03-04,2023-01-05 13:00:00,138705,9.340,True,Finance
4,Larry,Male,1998-01-24,2023-01-05 16:47:00,101004,1.389,True,Client Services
5,Dennis,Male,1987-04-18,2023-01-05 01:35:00,115163,10.125,False,Legal

In [162]:
# Salary column degeri 40000 ile 60000 arasinda olan degerler icin True, digerleri icin False degerler iceren bir series verir
# inclusive parametresi, verilen degerlerin dahil olup olmadigini belirtir, True ise degerler dahildir False ise degildir
# inclusive parametresinin varsayilan degeri True'dur
condition = employeesDataFrame['Salary'].between(40000, 60000, inclusive=True)

employeesDataFrame[condition].head()

C:\Users\umuty\AppData\Local\Temp\ipykernel_8728\2613535930.py:4: FutureWarning: Boolean inputs to the `inclusive` argument are deprecated in favour of `both` or `neither`.
  condition = employeesDataFrame['Salary'].between(40000, 60000, inclusive=True)

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
7,NaN,Female,2015-07-20,2023-01-05 10:43:00,45906,11.598,True,Finance
14,Kimberly,Female,1999-01-14,2023-01-05 07:13:00,41426,14.543,True,Finance
15,Lillian,Female,2016-06-05,2023-01-05 06:09:00,59414,1.256,False,Product
37,Linda,Female,1981-10-19,2023-01-05 20:49:00,57427,9.557,True,Client Services
51,NaN,NaN,2011-12-17,2023-01-05 08:29:00,41126,14.009,True,Sales

In [163]:
# Start Date column degeri belirtilen tarihler arasinda olan degerler icin True, digerleri icin False degerler iceren bir
# series dondurur
condition = employeesDataFrame["Start Date"].between("1985-01-01", "1995-01-01")

employeesDataFrame[condition].head()

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,1993-08-06,2023-01-05 12:42:00,97308,6.945,True,Marketing
2,Maria,Female,1993-04-23,2023-01-05 11:17:00,130590,11.858,False,Finance
5,Dennis,Male,1987-04-18,2023-01-05 01:35:00,115163,10.125,False,Legal
6,Ruby,Female,1987-08-17,2023-01-05 16:20:00,65476,10.012,True,Product
17,Shawn,Male,1986-12-07,2023-01-05 19:45:00,111737,6.414,False,Product

In [164]:
# Last Login Time column degeri belirtilen saatlar arasinda olan degerler icin True, digerler icin False degerler iceren 
# bir series dondurur
# inclusive=False ile inclusive='neither' ayni seydir
condition = employeesDataFrame["Last Login Time"].between("08:30 AM", "12:30 PM", inclusive="neither")

employeesDataFrame[condition].head()

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
2,Maria,Female,1993-04-23,2023-01-05 11:17:00,130590,11.858,False,Finance
7,NaN,Female,2015-07-20,2023-01-05 10:43:00,45906,11.598,True,Finance
10,Louise,Female,1980-08-12,2023-01-05 09:01:00,63241,15.132,True,NaN
18,Diana,Female,1981-10-23,2023-01-05 10:27:00,132940,19.082,False,Client Services
33,Jean,Female,1993-12-18,2023-01-05 09:07:00,119082,16.180,False,Business Development

In [165]:
# First Name column'undaki degerlerden tekrar eden varsa, ilk buldugu degere False sonradan ilk degerle ayni olan butun
# satirlara True deger atanmis bir series dondurur
# keep parametresini False olarak ayarlarsak, ilk bulunan degerden sonraki butun ayni degerlere True verir series icinde
# keep parametresini 'first' olarak ayarlarsak ilk bulunan degerden sonraki butun ayni degerlere True verir series icinde
# keep parametresini 'last' olarak ayarlarsak, tekrar eden degerlerden index olarak en buyuk olaninin (yani en sondaki)
# karsiliginda False, onceki tekrar eden degerlerin hepsine True atanacak bir series dondurur
condition = employeesDataFrame['First Name'].duplicated(keep=False)

employeesDataFrame[condition].head()

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,1993-08-06,2023-01-05 12:42:00,97308,6.945,True,Marketing
1,Thomas,Male,1996-03-31,2023-01-05 06:53:00,61933,4.170,True,NaN
2,Maria,Female,1993-04-23,2023-01-05 11:17:00,130590,11.858,False,Finance
3,Jerry,Male,2005-03-04,2023-01-05 13:00:00,138705,9.340,True,Finance
4,Larry,Male,1998-01-24,2023-01-05 16:47:00,101004,1.389,True,Client Services

In [166]:
# verilen series'deki boolean degerlerin degerini alabiliriz ~ operatoru ile
condition = [~condition]

In [167]:
# tekrar eden satirlardan ilkini tutup diger satirlari silinmis yeni bir dataframe dondurur
employeesDataFrame.drop_duplicates().head()

# tekrar eden degerleri aramak istedigimiz column'lari subset parametresi ile belirtebiliyoruz
# verilen column'lardaki tekrar eden deger iceren satirlarin ilkini tutup diger satirlari silinmis bir dataframe dondurur
employeesDataFrame.drop_duplicates(subset=['First Name', 'Team']).head()

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,1993-08-06,2023-01-05 12:42:00,97308,6.945,True,Marketing
1,Thomas,Male,1996-03-31,2023-01-05 06:53:00,61933,4.170,True,NaN
2,Maria,Female,1993-04-23,2023-01-05 11:17:00,130590,11.858,False,Finance
3,Jerry,Male,2005-03-04,2023-01-05 13:00:00,138705,9.340,True,Finance
4,Larry,Male,1998-01-24,2023-01-05 16:47:00,101004,1.389,True,Client Services

In [168]:
# verilen series icindeki degerlerin her birinden bir tane iceren bir numpy array dondurur
# NaN degeri de bir deger sayar
employeesDataFrame['First Name'].unique()[0:5]

array(['Douglas', 'Thomas', 'Maria', 'Jerry', 'Larry'], dtype=object)

In [169]:
# verilen series icindeki degerlerin her birinden bir tanesini sayacak sekilde deger dondurur
# NaN degeri saymaz varsayilan olarak
# dropna=False verilirse NaN'i da sayar
employeesDataFrame['First Name'].nunique(dropna=False)

201

In [170]:
bondDataFrame = pd.read_csv('resources/jamesbond.csv')
bondDataFrame.head()

,Film,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
0,Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
1,From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6
2,Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
3,Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
4,Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN

In [171]:
# asagidaki iki satirda da ayni islemi yaptik, ilki zaten olan bir dataframe'in index column'unu istedigimiz column ile
# degistirmemizi saglar
# ikinci column'da ise dataframe'i ice aktarirken index olarak ayarlamak istedigimiz column'u index_col parametresi
# ile belirtiriz
bondDataFrame.set_index(keys='Actor', inplace=True)
bondDataFrameWithFilmIndexColumn = pd.read_csv('resources/jamesbond.csv', index_col='Film')

In [172]:
# degistirdigimiz index_column'u orijinal haline getirir, drop=True yaparsak eski index column'u dataframe'den silinir
# inplace False ise degisikligin uygulandigi yeni bir dataframe dondurur, True ise degisikligi orijinal dataframe'e uygular
bondDataFrame.reset_index(drop=False, inplace=False).head()

,Actor,Film,Year,Director,Box Office,Budget,Bond Actor Salary
0,Sean Connery,Dr. No,1962,Terence Young,448.8,7.0,0.6
1,Sean Connery,From Russia with Love,1963,Terence Young,543.8,12.6,1.6
2,Sean Connery,Goldfinger,1964,Guy Hamilton,820.4,18.6,3.2
3,Sean Connery,Thunderball,1965,Terence Young,848.1,41.9,4.7
4,David Niven,Casino Royale,1967,Ken Hughes,315.0,85.0,NaN

In [173]:
temp = bondDataFrame.reset_index()
bondDataFrame2 = temp.drop_duplicates(subset='Actor')
bondDataFrame2.set_index(keys='Actor', inplace=True)
bondDataFrame2.head()

,Film,Year,Director,Box Office,Budget,Bond Actor Salary
Actor,,,,,,
Sean Connery,Dr. No,1962,Terence Young,448.8,7.0,0.6
David Niven,Casino Royale,1967,Ken Hughes,315.0,85.0,NaN
George Lazenby,On Her Majesty's Secret Service,1969,Peter R. Hunt,291.5,37.3,0.6
Roger Moore,Live and Let Die,1973,Guy Hamilton,460.3,30.8,NaN
Timothy Dalton,The Living Daylights,1987,John Glen,313.5,68.8,5.2

In [174]:
# verilen string turundeki index degerinin bulundugu satirlari, index olarak aldigi column adlarini bir series olarak dondurur
bondDataFrame2.loc['George Lazenby']

Film                 On Her Majesty's Secret Service
Year                                            1969
Director                               Peter R. Hunt
Box Office                                     291.5
Budget                                          37.3
Bond Actor Salary                                0.6
Name: George Lazenby, dtype: object

In [175]:
# verilen index'lerdeki satir araligini iceren bir dataframe dondurur
# slicing islemini python'daki gibi yapabiliriz
bondDataFrame2.loc['David Niven':'Roger Moore']
bondDataFrame2.loc['David Niven':'Roger Moore':2]

,Film,Year,Director,Box Office,Budget,Bond Actor Salary
Actor,,,,,,
David Niven,Casino Royale,1967,Ken Hughes,315.0,85.0,NaN
Roger Moore,Live and Let Die,1973,Guy Hamilton,460.3,30.8,NaN

In [176]:
# sectigimiz column'lari dataframe olarak dondurur
bondDataFrame2.loc[["David Niven", "Roger Moore", 'George Lazenby']]

,Film,Year,Director,Box Office,Budget,Bond Actor Salary
Actor,,,,,,
David Niven,Casino Royale,1967,Ken Hughes,315.0,85.0,NaN
Roger Moore,Live and Let Die,1973,Guy Hamilton,460.3,30.8,NaN
George Lazenby,On Her Majesty's Secret Service,1969,Peter R. Hunt,291.5,37.3,0.6

In [180]:
bondDataFrame.reset_index(inplace=True)
bondDataFrame.head()

,Actor,Film,Year,Director,Box Office,Budget,Bond Actor Salary
0,Sean Connery,Dr. No,1962,Terence Young,448.8,7.0,0.6
1,Sean Connery,From Russia with Love,1963,Terence Young,543.8,12.6,1.6
2,Sean Connery,Goldfinger,1964,Guy Hamilton,820.4,18.6,3.2
3,Sean Connery,Thunderball,1965,Terence Young,848.1,41.9,4.7
4,David Niven,Casino Royale,1967,Ken Hughes,315.0,85.0,NaN

In [182]:
# loc attribute ile yaptigimiz islemleri iloc ile sayisal index bazinda yapabiliriz
bondDataFrame.iloc[1:3]

,Actor,Film,Year,Director,Box Office,Budget,Bond Actor Salary
1,Sean Connery,From Russia with Love,1963,Terence Young,543.8,12.6,1.6
2,Sean Connery,Goldfinger,1964,Guy Hamilton,820.4,18.6,3.2

In [186]:
# iloc veya loc attribute'unda koseli parantez icine yazilan ve virgulle ayrilan iki degerden
# ilki, belirtilen index'leri secer. burada liste olarak istenen index'leri verebilir veya slicing yapabiliriz
# ikincisi, belirtilen column'lari secer. burada liste olarak istenen column'lar verilebilir veya slicing yapilabilir
# iloc kullanirsak index ve column'larin sayisal index'lerini vermek durumundayiz
# loc kullanirsak index ve column'larin string degerlerini vererek islem yapariz
bondDataFrame.iloc[[0, 2, 4], [1, 3, 5]]

            Film       Director  Budget
0         Dr. No  Terence Young     7.0
2     Goldfinger   Guy Hamilton    18.6
4  Casino Royale     Ken Hughes    85.0