In [62]:
import pandas as pd

In [63]:
bondDataFrame = pd.read_csv('resources/jamesbond.csv', index_col='Film')
bondDataFrame.sort_index(inplace=True)
bondDataFrame.head()

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9

In [64]:
# Actor sutunundaki degerleri 'Sean Connery'a esit olan satirlar icin True geri kalan satirlar icin False'a karsilik gelen
# boolean degerler iceren bir series dondurur
condition = bondDataFrame['Actor'] == 'Sean Connery'

# asagidaki iki satir, ayni sonucu uretir
bondDataFrame[condition]['Actor']
bondDataFrame.loc[condition, 'Actor'].head()

Film
Diamonds Are Forever     Sean Connery
Dr. No                   Sean Connery
From Russia with Love    Sean Connery
Goldfinger               Sean Connery
Never Say Never Again    Sean Connery
Name: Actor, dtype: object

In [65]:
# index degerlerini veya column adlarin degistirdigimiz bir dataframe dondurur:
# mapper, degistirilecek degerin key, yeni degerin value oldugu bir sozluk alir
# axis ise degistirilecek degerin index degeri mi yoksa column adi mi oldugunu belirtir, 0, index, 1, column degerlerini alabilir
# inplace, True verilirse degisiklik orijinal dataframe uzerinde yapilir False verilirse yeni bir dataframe dondurur
bondDataFrame.rename(mapper={
    'GoldenEye' : 'Golden Eye',
    'The World Is Not Enough' : 'Best Bond Movie Ever'
}, axis=0, inplace=False)

# bu kullanimda axis ve mapper parametrelerini tek bir sekilde verebiliyoruz
# index parametresine degisiklik yapilmasini istedigimiz index degerlerini key, yeni degerleri value olan bir sozluk veriyoruz
# column parametresine degisiklik yapilmasini istedigimiz column adlarini key, yeni adlari value olan bir sozluk veriyoruz
# ayni isimli birden fazla column veya ayni index'ten birden fazla varsa degisikligi butun column/index'ler uzerinde yapar
bondDataFrame.rename(index={
  'Casino Royale' : 'Casino Royale Updated'
}, inplace=False).head()

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
Casino Royale Updated,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Casino Royale Updated,1967,David Niven,Ken Hughes,315.0,85.0,NaN
Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9

In [66]:
# dataframe'in column isimlerini iceren bir index nesnesi dondurur
bondDataFrame.columns

temp = bondDataFrame.copy()

# column degerlerini kalici olarak degistirebiliriz 
temp.columns = ['Yil', 'Basrol', 'Yonetmen', 'Box Office', 'Butce(M$)', 'Basrol Maasi']
temp.head()

,Yil,Basrol,Yonetmen,Box Office,Butce(M$),Basrol Maasi
Film,,,,,,
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9

In [67]:
temp = bondDataFrame.copy()

# verilen index degerine denk gelen satiri silinmis yeni bir dataframe dondurur
# dataframe'de bulunmayan bir deger verilirsa hata alinir
# varsayilan olarak axis=0 yani index bazinda silme yapar, axis=1 dataframe'den column'u siler
# inplace parametresi mevcuttur
result = temp.drop('Casino Royale', inplace=False, axis=0)
result = temp.drop(['Casino Royale', 'Dr. No'], inplace=False)
result = temp.drop(['Box Office'], inplace=False, axis=1)

result.head()

,Year,Actor,Director,Budget,Bond Actor Salary
Film,,,,,
A View to a Kill,1985,Roger Moore,John Glen,54.5,9.1
Casino Royale,2006,Daniel Craig,Martin Campbell,145.3,3.3
Casino Royale,1967,David Niven,Ken Hughes,85.0,NaN
Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,34.7,5.8
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,154.2,17.9

In [77]:
temp = bondDataFrame.copy()

# degeri verilen column'u dataframe'den kalici olarak siler ve silinen column'u series olarak geri dondurur
result = temp.pop('Actor')

result.head()

Film
A View to a Kill           Roger Moore
Casino Royale             Daniel Craig
Casino Royale              David Niven
Diamonds Are Forever      Sean Connery
Die Another Day         Pierce Brosnan
Name: Actor, dtype: object

In [81]:
temp = bondDataFrame.copy()

# belirtilen column'u kalici olarak siler
del temp['Actor']

temp.head()

,Year,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,
A View to a Kill,1985,John Glen,275.2,54.5,9.1
Casino Royale,2006,Martin Campbell,581.5,145.3,3.3
Casino Royale,1967,Ken Hughes,315.0,85.0,NaN
Diamonds Are Forever,1971,Guy Hamilton,442.5,34.7,5.8
Die Another Day,2002,Lee Tamahori,465.4,154.2,17.9

In [97]:
# rastgele n sayida satir getirir
result = bondDataFrame.sample(n=1)

# dataframe'in satir sayisindan, belirtilen oran kadarini rastgele getirir
result = bondDataFrame.sample(frac=0.25)

# rastgele n sayidaki column'u getirir
result = bondDataFrame.sample(n=2, axis=1)

result.head()

                      Bond Actor Salary  Year
Film
A View to a Kill                    9.1  1985
Casino Royale                       3.3  2006
Casino Royale                       NaN  1967
Diamonds Are Forever                5.8  1971
Die Another Day                    17.9  2002

In [108]:
# verilen column'daki en buyuk n degeri bir dataframe ile dondurur
# verilen column'daki degerlere gore buyukten kucuge dogru siralanmistir
bondDataFrame.nlargest(3, 'Box Office')

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
Skyfall,2012,Daniel Craig,Sam Mendes,943.5,170.2,14.5
Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2

In [106]:
# verilen column'daki en kucuk n degeri bir dataframe ile dondurur
# verilen column'daki degerlere gore kucukten buyuge dogru siralanmistir
bondDataFrame.nsmallest(3, 'Box Office')

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
Licence to Kill,1989,Timothy Dalton,John Glen,250.9,56.7,7.9
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
On Her Majesty's Secret Service,1969,George Lazenby,Peter R. Hunt,291.5,37.3,0.6

In [120]:
# dataframe'de belirtilen kosula uyan satirlari aynen tutarken, uyumayan satirlardaki verileri NaN ile degistirilmis
# yeni bir dataframe dondurur
result = bondDataFrame.where(bondDataFrame['Actor']=='Roger Moore')
result = bondDataFrame.where((bondDataFrame['Actor']=='Sean Connery') & (bondDataFrame['Bond Actor Salary']>3))

# dropna ile NaN verilerin bulundugu satirlari silerek dataframe'i temizleyebiliriz
result = result.dropna()

result

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
Diamonds Are Forever,1971.0,Sean Connery,Guy Hamilton,442.5,34.7,5.8
Goldfinger,1964.0,Sean Connery,Guy Hamilton,820.4,18.6,3.2
Thunderball,1965.0,Sean Connery,Terence Young,848.1,41.9,4.7
You Only Live Twice,1967.0,Sean Connery,Lewis Gilbert,514.2,59.9,4.4

In [149]:
temp = bondDataFrame.copy()

# query metodu ile string olarak dataframe icin sorgu yazabiliyoruz ama column adinda bosluk varsa hata aliriz
result = temp.query("Actor == 'Roger Moore'")
result = temp.query("Year > 600")

# column adlarindaki bosluklari su sekilde ortadan kaldirabiliriz
temp.columns = [columnName.replace(' ', '_') for columnName in temp.columns]

result = temp.query('Box_Office > 600')
result = temp.query("Actor == 'Roger Moore' and Director=='John Glen'")
result = temp.query("Actor in ['Timothy Dalton', 'George Lazenby']")



result.head()

,Year,Actor,Director,Box_Office,Budget,Bond_Actor_Salary
Film,,,,,,
Licence to Kill,1989,Timothy Dalton,John Glen,250.9,56.7,7.9
On Her Majesty's Secret Service,1969,George Lazenby,Peter R. Hunt,291.5,37.3,0.6
The Living Daylights,1987,Timothy Dalton,John Glen,313.5,68.8,5.2

In [158]:
addCurrency = lambda text : str(text) + ' Million $'

# apply, kendisine verilen tek parametreli fonksiyonu series'in butun elemanlarina uygulayip, degisen elemanlardan olusan
# yeni bir series dondurur
bondDataFrame['Bond Actor Salary'].apply(addCurrency).head()

Film
A View to a Kill         9.1 Million $
Casino Royale            3.3 Million $
Casino Royale            nan Million $
Diamonds Are Forever     5.8 Million $
Die Another Day         17.9 Million $
Name: Bond Actor Salary, dtype: object

In [193]:
def doFilter(row):
    if(row[1] == 'Sean Connery'):
        return 'anladim'
    return 'test'

# axis=0 ile
# her column'u birer series olarak verilen fonksiyona gecer
# yani apply ile bir kere cagiririz ama column sayisi kadar calisir bu fonksiyon
# her seferinde de bir column'u series halinda arguman olarak fonksiyona gonderir
bondDataFrame.apply(doFilter, axis=0)

Year                 test
Actor                test
Director             test
Box Office           test
Budget               test
Bond Actor Salary    test
dtype: object

In [200]:
chicagoDataFrame = pd.read_csv('resources/chicago.csv')

chicagoDataFrame.head()

,Name,Position Title,Department,Employee Annual Salary
0,"AARON, ELVIA J",WATER RATE TAKER,WATER MGMNT,$90744.00
1,"AARON, JEFFERY M",POLICE OFFICER,POLICE,$84450.00
2,"AARON, KARINA",POLICE OFFICER,POLICE,$84450.00
3,"AARON, KIMBERLEI R",CHIEF CONTRACT EXPEDITER,GENERAL SERVICES,$89880.00
4,"ABAD JR, VICENTE M",CIVIL ENGINEER IV,WATER MGMNT,$106836.00

In [238]:
# verilen column'daki degerlerin ilk harflerini buyuk, gerisini kucuk yaparak ilgili column'u yeni bir series olarak dondurur
result = chicagoDataFrame['Department'].str.title()

# verilen column'daki degerlerin butun harflerini kucuk yaparak ilgili column'u yeni bir series olarak dondurur
result = chicagoDataFrame['Department'].str.lower()

# verilen column'daki degerlerin karakter sayilarini yeni bir series olarak dondurur
result = chicagoDataFrame['Department'].str.len()

# verilen column'daki degerlerdeki belirtilen kisimlari degistirerek ilgili column'u yeni bir series olarak dondurur
# regex kullanip kullanamayacagimizi belirtebiliyoruz
result = chicagoDataFrame['Department'].str.replace('MGMNT', 'MANAGEMENT', regex=False)

# verilen column'daki degerlerin verilen karakterlerle baslayip baslamadigina gore bir bool series dondurur
result = chicagoDataFrame['Department'].str.startswith('W')

# verilen column'daki degerlerin bastan ve sondan verilen karakterleri varsa silinmis yeni bir series dondurur
# arguman verilmezse bosluklari siler
result = chicagoDataFrame['Department'].str.strip('W')


# verilen column'lardaki degerlerin her birini verilen karakterlerden bolerek, bolunmus parcalari liste olarak dondurur
result = chicagoDataFrame['Name'].str.split(',')

# verilen listelerin sifirnci indexli elemanlarini iceren bir series dondurur
result = chicagoDataFrame['Name'].str.split(',').str.get(0)

result.head()

0      AARON
1      AARON
2      AARON
3      AARON
4    ABAD JR
Name: Name, dtype: object