In [3]:
import pandas as pd

In [4]:
tempSeries = pd.Series([1, 2, 3, 4, 5, None ,7, 8])
tempSeries

0    1.0
1    2.0
2    3.0
3    4.0
4    5.0
5    NaN
6    7.0
7    8.0
dtype: float64

In [5]:
# NaN olmayan degerlerin sayisini dondurur
tempSeries.count()

7

In [6]:
nbaDataFrame = pd.read_csv('resources/nba.csv')
nbaDataFrame

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0
...,...,...,...,...,...,...,...,...,...
453,Shelvin Mack,Utah Jazz,8.0,PG,26.0,6-3,203.0,Butler,2433333.0
454,Raul Neto,Utah Jazz,25.0,PG,24.0,6-1,179.0,NaN,900000.0
455,Tibor Pleiss,Utah Jazz,21.0,C,26.0,7-3,256.0,NaN,2900000.0
456,Jeff Withey,Utah Jazz,24.0,C,26.0,7-0,231.0,Kansas,947276.0
457,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
# birden fazla column oldugu icin her satirdaki verileri liste olarak iceren bir numpy array donduruyor
nbaDataFrame.values

array([['Avery Bradley', 'Boston Celtics', 0.0, ..., 180.0, 'Texas',
        7730337.0],
       ['Jae Crowder', 'Boston Celtics', 99.0, ..., 235.0, 'Marquette',
        6796117.0],
       ['John Holland', 'Boston Celtics', 30.0, ..., 205.0,
        'Boston University', nan],
       ...,
       ['Tibor Pleiss', 'Utah Jazz', 21.0, ..., 256.0, nan, 2900000.0],
       ['Jeff Withey', 'Utah Jazz', 24.0, ..., 231.0, 'Kansas', 947276.0],
       [nan, nan, nan, ..., nan, nan, nan]], dtype=object)

In [8]:
# column'lardaki degerler ayni turden ise dondurur, farkli turden veriler ise object dondurebilir
# column'daki degerlerden en az biri NaN ise float64 olarak belirtilir
nbaDataFrame.dtypes

Name         object
Team         object
Number      float64
Position     object
Age         float64
Height       object
Weight      float64
College      object
Salary      float64
dtype: object

In [9]:
# column adlarini iceren bir Index nesnesi dondurur
nbaDataFrame.columns

Index(['Name', 'Team', 'Number', 'Position', 'Age', 'Height', 'Weight',
       'College', 'Salary'],
      dtype='object')

In [10]:
# ilki index degerlerini, ikincisi column adlarini belirten bir liste dondurur
nbaDataFrame.axes

[RangeIndex(start=0, stop=458, step=1),
 Index(['Name', 'Team', 'Number', 'Position', 'Age', 'Height', 'Weight',
        'College', 'Salary'],
       dtype='object')]

In [11]:
# dataframe ile ilgili meta bilgileri iceren bir dataframe dondurur
nbaDataFrame.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 458 entries, 0 to 457
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      457 non-null    object
 1   Team      457 non-null    object
 2   Number    457 non-null    float64
 3   Position  457 non-null    object
 4   Age       457 non-null    float64
 5   Height    457 non-null    object
 6   Weight    457 non-null    float64
 7   College   373 non-null    object
 8   Salary    446 non-null    float64
dtypes: float64(4), object(5)
memory usage: 32.3+ KB

In [12]:
revenueDataFrame = pd.read_csv('resources/revenue.csv', index_col='Date')

In [13]:
# column'larin toplamlarinin degerler, column isimlerinin index oldugu yeni bir dataframe dondurur
revenueDataFrame.sum()
revenueDataFrame.sum(axis=0)
revenueDataFrame.sum(axis='index')

New York       5475
Los Angeles    5134
Miami          5641
dtype: int64

In [14]:
# row'lardaki degerleri toplayarak sonuclarini ayni row'un index degeri ile yeni bir dataframe dondurur
revenueDataFrame.sum(axis=1)
revenueDataFrame.sum(axis='columns')

Date
1/1/16     1606
1/2/16     2060
1/3/16      967
1/4/16     2519
1/5/16      438
1/6/16     1935
1/7/16     1234
1/8/16     2313
1/9/16     2623
1/10/16     555
dtype: int64

In [15]:
# column'lara erismek icin su syntax kullanilabilinir
revenueDataFrame['Miami']

Date
1/1/16     499
1/2/16     534
1/3/16     933
1/4/16     885
1/5/16     253
1/6/16     497
1/7/16     115
1/8/16     886
1/9/16     823
1/10/16    216
Name: Miami, dtype: int64

In [16]:
# birden fazla column'u secmek icin su syntax kullanilabilir
revenueDataFrame[['Miami', 'New York']]

         Miami  New York
Date
1/1/16     499       985
1/2/16     534       738
1/3/16     933        14
1/4/16     885       730
1/5/16     253       114
1/6/16     497       936
1/7/16     115       123
1/8/16     886       935
1/9/16     823       846
1/10/16    216        54

In [21]:
# column'lar arasinda bulunmayan bir degeri bu sekilde eklersek butun satirlara eklenir
revenueDataFrame['Isparta'] = 500
revenueDataFrame

         New York  Los Angeles  Miami  Isparta
Date
1/1/16        985          122    499      500
1/2/16        738          788    534      500
1/3/16         14           20    933      500
1/4/16        730          904    885      500
1/5/16        114           71    253      500
1/6/16        936          502    497      500
1/7/16        123          996    115      500
1/8/16        935          492    886      500
1/9/16        846          954    823      500
1/10/16        54          285    216      500

In [23]:
# dataframe'deki veriler ile belirtilen yola yeni bir csv dosyasi olusturur
revenueDataFrame.to_csv('resources/new_revenue.csv')

In [29]:
# loc parametresi ile column'larin arasindaki index'i, 
# column parametresi ile yeni column adini,
# value parametresi ile yeni column'un degerlerini veriyoruz, value parametresi olarak satir sayisina esit bir liste de verebiliriz
# allow_duplicates parametresi ile, yeni column adinda bir column'un zaten dataframe'de olmasi halinde insert isleminin yapilip yapilmayacagini belirtir
revenueDataFrame.insert(loc=4, column='Istanbul', value=650, allow_duplicates=False)

# yukaridaki kullanim ile bu kullanim aynidir
revenueDataFrame.insert(4, 'Istanbul', 650)

In [34]:
# yeni column degerlerini bir series veya liste yardimiyla ekleyebiliriz
revenueDataFrame['Izmir'] = revenueDataFrame['Los Angeles'] + 25

In [37]:
# bir series'in mul metodu ile butun degerlerini verilen parametre ile carpma islemine sokabiliyoruz
revenueDataFrame['Izmir'] = (revenueDataFrame['Izmir']).mul(1.25)

In [38]:
# bir sutundaki ogelerin frekanslarini hesaplar
revenueDataFrame.value_counts()

New York  Los Angeles  Miami  Isparta  Istanbul  Izmir
14        20           933    500      650       70.3125      1
54        285          216    500      650       484.3750     1
114       71           253    500      650       150.0000     1
123       996          115    500      650       1595.3125    1
730       904          885    500      650       1451.5625    1
738       788          534    500      650       1270.3125    1
846       954          823    500      650       1529.6875    1
935       492          886    500      650       807.8125     1
936       502          497    500      650       823.4375     1
985       122          499    500      650       229.6875     1
dtype: int64

In [42]:
# series'in degerlerinin frekanslarini hesaplar
# ascending parametresi ile artan siralama islemi yapabiliriz
# normalize parametresi ile frekanslarin yuzdelik olarak hesaplanmasini saglayabiliriz
revenueDataFrame['Izmir'].value_counts(ascending=True, normalize=True)

229.6875     0.1
1270.3125    0.1
70.3125      0.1
1451.5625    0.1
150.0000     0.1
823.4375     0.1
1595.3125    0.1
807.8125     0.1
1529.6875    0.1
484.3750     0.1
Name: Izmir, dtype: float64

In [43]:
# dataframe'deki NaN degerleri ortadan kaldirmaya yarar
# axis=0 ise satir bazinda arama yapilir, axis=1 ise sutun bazinda arama yapilir, varsayilan 0'dir
# how='any', satir veya sutundaki herhangi bir deger NaN ise siler, how='all' ise satir veya sutundaki tum degerler NaN ise silme yapar
# subset ile NaN degerleri aratacagimiz column'lari belirtebiliriz
# inplace=False ise NaN degerlerinin silindigi yeni bir dataframe dondurur, inplace=True ise orijinal dataframe uzerinde degisiklik yapar
revenueDataFrame.dropna(axis=0, how='any', subset=['Izmir', 'Isparta'], inplace=False)

         New York  Los Angeles  Miami  Isparta  Istanbul      Izmir
Date
1/1/16        985          122    499      500       650   229.6875
1/2/16        738          788    534      500       650  1270.3125
1/3/16         14           20    933      500       650    70.3125
1/4/16        730          904    885      500       650  1451.5625
1/5/16        114           71    253      500       650   150.0000
1/6/16        936          502    497      500       650   823.4375
1/7/16        123          996    115      500       650  1595.3125
1/8/16        935          492    886      500       650   807.8125
1/9/16        846          954    823      500       650  1529.6875
1/10/16        54          285    216      500       650   484.3750

In [ ]:
# dataframe'deki NaN degerlerin arguman olarak verilen degerle degistirilmesini saglar
revenueDataFrame.fillna(0)

In [45]:
# dataframe'deki NaN alanlar yerine True, geri kalan alanlar icin False degeri bulunduran bir dataframe dondurur
revenueDataFrame.isna()

         New York  Los Angeles  Miami  Isparta  Istanbul  Izmir
Date
1/1/16      False        False  False    False     False  False
1/2/16      False        False  False    False     False  False
1/3/16      False        False  False    False     False  False
1/4/16      False        False  False    False     False  False
1/5/16      False        False  False    False     False  False
1/6/16      False        False  False    False     False  False
1/7/16      False        False  False    False     False  False
1/8/16      False        False  False    False     False  False
1/9/16      False        False  False    False     False  False
1/10/16     False        False  False    False     False  False

In [49]:
# series'de NaN eleman varsa True, yoksa False dondurur
revenueDataFrame['Izmir'].hasnans

False

In [53]:
# verilen series'deki verilerin type'ini uygunsa arguman olarak verilen turde ayarlar
# NaN deger varsa hata verir
revenueDataFrame['Izmir'].astype('int')

Date
1/1/16      229
1/2/16     1270
1/3/16       70
1/4/16     1451
1/5/16      150
1/6/16      823
1/7/16     1595
1/8/16      807
1/9/16     1529
1/10/16     484
Name: Izmir, dtype: int32

In [59]:
# series'deki essiz degerleri iceren bir numpy array dondurur
revenueDataFrame['Izmir'].unique()

array([ 229.6875, 1270.3125,   70.3125, 1451.5625,  150.    ,  823.4375,
       1595.3125,  807.8125, 1529.6875,  484.375 ])

In [62]:
# series'deki essiz degerlerin sayisini verir
revenueDataFrame['Izmir'].nunique()

10

In [66]:
# dataframe'deki verileri New York column'unun artan siralanmasina gore duzenler
# ascending=True olursa azalan sekilde siralar
revenueDataFrame.sort_values('New York', ascending=False)
revenueDataFrame.sort_values(by='New York')

         New York  Los Angeles  Miami  Isparta  Istanbul      Izmir
Date
1/3/16         14           20    933      500       650    70.3125
1/10/16        54          285    216      500       650   484.3750
1/5/16        114           71    253      500       650   150.0000
1/7/16        123          996    115      500       650  1595.3125
1/4/16        730          904    885      500       650  1451.5625
1/2/16        738          788    534      500       650  1270.3125
1/9/16        846          954    823      500       650  1529.6875
1/8/16        935          492    886      500       650   807.8125
1/6/16        936          502    497      500       650   823.4375
1/1/16        985          122    499      500       650   229.6875

In [67]:
# na_position parametresini NaN iceren satirlari yeni dataframe'in neresinde gosterilecegini belirler
# first ise basta, last ise sonda gosterir. varsayilan olarak last olarak gelir
revenueDataFrame.sort_values(by='New York', na_position='first')

         New York  Los Angeles  Miami  Isparta  Istanbul      Izmir
Date
1/3/16         14           20    933      500       650    70.3125
1/10/16        54          285    216      500       650   484.3750
1/5/16        114           71    253      500       650   150.0000
1/7/16        123          996    115      500       650  1595.3125
1/4/16        730          904    885      500       650  1451.5625
1/2/16        738          788    534      500       650  1270.3125
1/9/16        846          954    823      500       650  1529.6875
1/8/16        935          492    886      500       650   807.8125
1/6/16        936          502    497      500       650   823.4375
1/1/16        985          122    499      500       650   229.6875

In [68]:
# once ilk column'a gore azalan, sonra siralanan degerleri kendi icinde ikinci column'a gore artan siralar
revenueDataFrame.sort_values(by=['New York', 'Istanbul'], ascending=[True, False])

         New York  Los Angeles  Miami  Isparta  Istanbul      Izmir
Date
1/3/16         14           20    933      500       650    70.3125
1/10/16        54          285    216      500       650   484.3750
1/5/16        114           71    253      500       650   150.0000
1/7/16        123          996    115      500       650  1595.3125
1/4/16        730          904    885      500       650  1451.5625
1/2/16        738          788    534      500       650  1270.3125
1/9/16        846          954    823      500       650  1529.6875
1/8/16        935          492    886      500       650   807.8125
1/6/16        936          502    497      500       650   823.4375
1/1/16        985          122    499      500       650   229.6875

In [70]:
# index'leri siralar
revenueDataFrame.sort_index()

         New York  Los Angeles  Miami  Isparta  Istanbul      Izmir
Date
1/1/16        985          122    499      500       650   229.6875
1/10/16        54          285    216      500       650   484.3750
1/2/16        738          788    534      500       650  1270.3125
1/3/16         14           20    933      500       650    70.3125
1/4/16        730          904    885      500       650  1451.5625
1/5/16        114           71    253      500       650   150.0000
1/6/16        936          502    497      500       650   823.4375
1/7/16        123          996    115      500       650  1595.3125
1/8/16        935          492    886      500       650   807.8125
1/9/16        846          954    823      500       650  1529.6875

In [72]:
nbaDataFrame = pd.read_csv('resources/nba.csv').dropna(how='all')
nbaDataFrame['Salary'] = nbaDataFrame['Salary'].fillna(0).astype('int')

In [76]:
# rank'lari kucukten buyuge dogru siralar
nbaDataFrame['Salary'].rank(ascending=False)

0       97.0
1      110.0
2      452.0
3      322.0
4      147.0
       ...
452    250.0
453    241.0
454    383.0
455    214.5
456    367.0
Name: Salary, Length: 457, dtype: float64